### ISSUE TITLE
The Turing Way Editions

### ISSUE THREAD

**Issue by myyong** [alan-turing-institute/bio-Turing-Way#19]
1. First prototype for ["The Turing Way - Editions"](https://the-turing-way-customise.netlify.app) found here:

To achieve this the user has to configure `profile.yaml`. An example for two editions `dsg` and `enrichment`can be configured the following way:

```YAML
dsg:
  - welcome
  - communication/communication
  - communication/comms-overview
  - communication/comms-overview/comms-overview-principles
enrichment:
  - welcome
  - reproducible-research/reproducible-research
  - reproducible-research/overview
  - reproducible-research/overview/overview-definitions
```

In order to create a new `group-leader`edition, the user adds to `profile.yaml` as follows, by including all pages relevant to that edition.

```YAML
dsg:
  - welcome
  - communication/communication
  - communication/comms-overview
  - communication/comms-overview/comms-overview-principles
enrichment:
  - welcome
  - reproducible-research/reproducible-research
  - reproducible-research/overview
group-leader:
  - welcome
  - project-design/project-design
  - project-design/pd-overview
  - project-design/pd-overview/pd-overview-planning
  - project-design/pd-overview/pd-overview-repro
  - project-design/pd-overview/pd-overview-method
  - project-design/pd-overview/pd-overview-version
```

2. Use the cards as shown in the image to navigate between the editions:

<img width="1473" alt="Screenshot 2021-11-30 at 13 58 03" src="https://user-images.githubusercontent.com/5417696/144060626-09ece7cf-8f29-4658-a7a7-c248cdcbd7bc.png">

Next step: We are currently working on fixing the hyperlinks within the cards. The current deployed version navigates to the correct edition, but does not link to any specific section.
